#!/bin/bash
##
#$ -S /bin/bash
#$ -pe smp 128
#$ -q COE,UI
#$ -j y
#$ -cwd
#$ -N maker
#$ -o $JOB_NAME.$TASK_ID.log 
#$ -ckpt user 
#$ -l std_mem
#$ -M austin-ward@uiowa.edu
#$ -m bea

####This is an example submission script qsub.sh
####$ -l mid_mem
####$ -l high_mem
####This is an example submission script qsub.sh
#SGE_TASK_ID=5
MAKER=/Users/acward/Earthworm_project/tools/maker/bin
MASKED_ASSEMBLY=/Users/acward/Earthworm_project/data/Earthworm_Genomes/NHHW161454/genome_$SGE_TASK_ID/SPADES_assembly_MultiKmer
date

cd /Users/acward/Earthworm_project/data/Earthworm_Genomes/NHHW161454/genome_$SGE_TASK_ID/Annotation

$MAKER/maker -genome $MASKED_ASSEMBLY/scaffolds.fasta.masked -c 128

cd scaffolds.fasta.maker.output 
perl /Users/acward/Earthworm_project/tools/maker/bin/gff3_merge -d scaffolds.fasta_master_datastore_index.log
date


##################################:
