#!/bin/bash
##
#$ -S /bin/bash
#$ -pe smp 16
#$ -q COE,UI
#$ -j y
#$ -cwd
#$ -N masking_lib
#$ -o $JOB_NAME.$TASK_ID.log 
#$ -ckpt user
#$ -l std_mem
#$ -M austin-ward@uiowa.edu
#$ -m bea
####This is an example submission script qsub.sh
####$ -l mid_mem
####$ -l high_mem
####This is an example submission script qsub.sh

#SGE_TASK_ID=2

REPEATMODELER=/Users/acward/Earthworm_project/tools/RepeatModeler-open-1.0.10
REPEATMASKER=/Users/acward/Earthworm_project/tools/RepeatMasker

ASSEMBLY=/Users/acward/Earthworm_project/data/Earthworm_Genomes/NHHW161454/genome_$SGE_TASK_ID/SPADES_assembly_MultiKmer
DATABASE=/Users/acward/Earthworm_project/data/Earthworm_Genomes/NHHW161454/genome_$SGE_TASK_ID/Masking/Database

OUTPUT=/Users/acward/Earthworm_project/data/Earthworm_Genomes/NHHW161454/genome_$SGE_TASK_ID/Masking/RepeatModeler

date

#Build Database

cd $DATABASE
$REPEATMODELER/BuildDatabase -name genome_$SGE_TASK_ID -engine ncbi $ASSEMBLY/scaffolds.fasta

date 

#Run RepeatModeler
cd $OUTPUT
$REPEATMODELER/RepeatModeler -engine ncbi -pa 16 -database $DATABASE/genome_$SGE_TASK_ID > run.out

date

#Run RepeatMasker
cd /Users/acward/Earthworm_project/data/Earthworm_Genomes/NHHW161454/genome_$SGE_TASK_ID/Masking/RepeatModeler/RM*
$REPEATMASKER/RepeatMasker -pa 16 -lib consensi.fa $ASSEMBLY/scaffolds.fasta



##################################:
